nome = str(input('Digite seu nome completo: '))
print('Analisando seu nome...')
print(f'Seu nome em maiúsculas é {(nome.upper())}')
print(f'Seu nome em minúsculas é {(nome.lower())}')
print(f'Seu nome tem: {len(nome.strip())}')
print(f'Possui: {(len(nome.split()[0]))} letras em seu primeiro nome')
