a = input('Digite algo para saber seu tipo primitivo: ')
print ('O tipo primitivo desse valor é ', type (a))
print (' Só tem espaços?', a.isspace())
print (' É um número?', a.isnumeric())
print (' É alfabético', a.isalpha())